services:
  stagepass_db:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_DB: "stagepass_db"
      POSTGRES_USER: "stagepass_server"
      POSTGRES_PASSWORD: "60009172"
    ports:
      - "5432:5432"
    volumes:
      - stagepass_db_data:/var/lib/postgresql_11/data

  # stagepass_server:
  #   build: .
  #   container_name: stagepass_server
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - stagepass_network
  #   depends_on:
  #     - stagepass_db
  #   volumes:
  #     - .:/usr/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  stagepass_network:
    driver: bridge

volumes:
  stagepass_db_data:
